# java -jar ksqldb-std-artifact-generator-1.0.1.jar --spring.config.location=anotherApplication.yml
server:
  port:  8099

model:
  restProxyUrl: http://rest-proxy:8082/v3/clusters/OL54Eo6DR6WhVRrUV7YN_w/consumer-groups
  lag: 0
  isSimulation: false
  topics: ^(COM|CAI|SGS)_.*$   #regexp filter,  ^.*$ if you don't want any filter'

# POST http://localhost:8082/v3/clusters/{cluster_id}/topics/{topic_name}/configs:alter => dynamic configuration to be applied (SET) or undone (DELETE)
  topicConfigsAlter: >
      {
        "data": [
          {
            "name": "cleanup.policy",
            "operation": "DELETE"
          },
          {
            "name": "compression.type",
            "value": "gzip",
             "operation": "SET"
          },
          {
            "name": "retention.ms",
            "value": "3600000",
            "operation": "SET"
          }        ]
      }

   
   