# java -jar ksqldb-std-artifact-generator-1.0.1.jar --spring.config.location=anotherApplication.yml
server:
  port:  8099

model:
  restProxyUrl: http://localhost:8082/v3/clusters/OL54Eo6DR6WhVRrUV7YN_w/topics%s
  
  isSimulation: false
  topics: ^(COM|CAI|SGS)_T.*$   #regexp filter,  ^.*$ if you don't want any filter'

# POST http://localhost:8082/v3/clusters/{cluster_id}/topics/{topic_name}/configs:alter => dynamic configuration to be applied (SET) or undone (DELETE)
# retention.ms: 8640000000000 = 273 years 9 months, should be enough
  topicConfigsAlter: >
      {
        "data": [
          {
            "name": "cleanup.policy",
            "operation": "DELETE"
          },
          {
            "name": "retention.ms",
            "value": "8640000000000",
            "operation": "SET"
          }        ]
      }

   
   