# java -jar ksqldb-tgen-artifact-generator-1.0.0.jar --spring.config.location=anotherApplication.yml
connect:
  #connectionUrl: jdbc:sqlserver://SSUAVE1043.AD.CH.PBK:1112;databaseName=SG_SGS
  connectionUrl: jdbc:sqlserver://ESUAVE1043.AD.CH.PBK:1111;databaseName=SG_SGS_CPT;authenticationScheme=NTLM;integratedSecurity=true;user=ct332;password=Welcome2021++
  databaseAndSchema: SG_SGS_CPT.cpt
#  connectionUser: ADMLOAD
#  connectionPassword: jdEa#b.Xm(7l
  connectionUser: ct332
  connectionPassword: Welcome2021++
  ksqlUrl: http://localhost:8088

tgen:
  tabgenConfig: classpath:tabgenConfig.yml
  tabgenStream: SGS_TAB_GEN_STD_S01
  createStreams: true
  createConnectors: true
  dropStreams: true
  dropConnectors: true
  isSimulation: false
  codes: ALL  # comma separated list of codes to generate (taken from the tabgenConfig.yml file) or ALL 
